//
// Created by luana on 4/30/2020.
//

#ifndef HOMEWORK_2___THE_SHOOTOUT_BULLETPROOFVEST_H
#define HOMEWORK_2___THE_SHOOTOUT_BULLETPROOFVEST_H


class BulletproofVest {

};


#endif //HOMEWORK_2___THE_SHOOTOUT_BULLETPROOFVEST_H
